### ISSUE TITLE
Spores don't prevent capture of `this`

### ISSUE THREAD

**Issue by dimbleby** [heathermiller/spores#43]
I'm using spores-core 0.2.1.

Motivating example at SIP-21 is use of `Future`s in Akka, and the following code is given:

```scala
    def receive = {
      case Request(data) =>
        Future(spore {
          val from = sender
          val d = data
          () => {
            val result = transform(d)
            from ! Response(result)
          }
       })
    }
```

with commentary "In this case, the problematic capturing of `this` is avoided, since the result of `this.sender` is assigned to the spore's local value from when the spore is created. The spore conformity checking ensures that within the spore's closure, only `from` and `d` are used."

But the following code compiles just fine:

```scala
    def receive = {
      case Request(data) =>
        Future(spore {
          val d = data
          () => {
            val result = transform(d)
            sender ! Response(result)
          }
       })
    }
```

... which seems to say that spores just aren't helping, in the exact case where they're supposed to help.

What have I misunderstood?!

**Comment by jvican** [comment]
Hi @dimbleby, thanks for passing by.
  
This PR https://github.com/heathermiller/spores/pull/44 does show that the expected behaviour is indeed to throw errors for uncaptured variables. I just tried to model the akka logic very badly (don't pay attention to it) so that i can copy/paste your code from here to convince you that it works.
  
Despite the example I provide works, it looks like you may have found a corner case that our macros are not handling. In order to fix it, it would be useful if you can share that code or, even better, to submit a PR just like the one I did showing that your example fails.
  
As a side note, you got the concept correctly.

**Comment by dimbleby** [comment]
Hi, thanks for the quick response.

I've put a complete (but small) example project [here](https://github.com/dimbleby/spores-experiment) - in particular, see [these lines](https://github.com/dimbleby/spores-experiment/blob/c2f54f7d4127b221225238bd9b4a28867164e4f9/src/main/scala/PingPongTest.scala#L44-L49).

**Comment by jvican** [comment]
Great! I think it's a bug that should have a rather straightforward fix. Have you been able to reproduce it without the use of `delayed`?

**Comment by dimbleby** [comment]
Sure, it makes no difference.

**Comment by jvican** [comment]
Nice, I'll work on it and get back to you when I get it solved. Thanks for the error report!

**Comment by jvican** [comment]
Hi @dimbleby, as I expected, this issue only occurs in `0.2.1`, but it doesn't in the most up-to-date `0.2.3` version. I've just added three tests that replicate **exactly** your toy project, and they fail. When cloning your project and changing spores version to `0.2.3` AND publishing locally, the project compiles just fine.
  
We're due to cut a release very soon. If you find yourself in a hurry, publish locally via sbt. Hope to have solved your problem, I'll be waiting for your confirmation.

**Comment by dimbleby** [comment]
Great, thanks.  I'll look forward to trying again with the new release.

If you're satisfied that this is fixed, please feel free to close the issue without waiting for my confirmation - I can always open a new one if I still see problems!

**Comment by jvican** [comment]
Great, thanks!
  
Let's do that. You can see that tests are passing https://github.com/heathermiller/spores/pull/44.
